---
# These are supported funding model platforms

github: # [user1, user2]
patreon: GameTec_live
open_collective: # Open Collective username
ko_fi: # Ko-fi username
tidelift: # npm/babel
community_bridge: # cloud-foundry
liberapay: # Liberapay username
issuehunt: # IssueHunt username
otechie: # Otechie username
lfx_crowdfunding: # cloud-foundry
custom: # ['link1', 'link2']
